services:
  kitsu:
    build: .  # ğŸ”„ ì´ ë¯¸ ì§€  ëŒ€ ì‹   ë¡œ ì»¬ ì— ì„œ  ì§ ì ‘  ë¹Œ ë“œ
    container_name: kitsu
    networks:
      - traefik_default
    environment:
      - ADDON_URL=http://hspki1.duckdns.org
      - FANART_APIKEY=1ab9fadecde8115ed16e0adfcfdcf485
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kitsu.rule=Host(`hspki1.duckdns.org`)"
      - "traefik.http.routers.kitsu.entrypoints=web,websecure"
      - "traefik.http.routers.kitsu.tls=true"
      - "traefik.http.routers.kitsu.tls.certresolver=production"
      - "traefik.http.services.kitsu.loadbalancer.server.port=7000"
    restart: unless-stopped
networks:
  traefik_default:
    external: true
